In [1]:
import numpy as np

# Step 1: Define the fixed 3x4 matrix
matrix_3x4 = np.array([[13, 16, 1, 4],
                       [4, 8, 10, 20],
                       [19, 5, 7, 13]])

# Extract Coefficient Matrix (A) and Right-hand Side Vector (b)
A = matrix_3x4[:, :3]  # First 3 columns
b = matrix_3x4[:, 3]   # Last column

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Generated 3x4 Matrix:
[[13 16  1  4]
 [ 4  8 10 20]
 [19  5  7 13]]

Coefficient Matrix (A):
[[13 16  1]
 [ 4  8 10]
 [19  5  7]]

Right-hand Side Vector (b):
[ 4 20 13]

Solution using Matrix Inverse Method:
[-0.05516154  0.17730496  1.88022065]

Solution using Gaussian Elimination (NumPy):
[-0.05516154  0.17730496  1.88022065]

Verification (Ax = b):
[ 4. 20. 13.]
