```
Q1: What are some examples of unary operations in matrices? Write your answer below:

```

Unary operations are operations that apply to a single matrix. Examples of unary operations include:

>Transpose: Flipping the matrix over its diagonal, changing rows into columns and vice versa.

>Trace: The sum of the diagonal elements of the matrix.

>Determinant: A scalar value that represents certain properties of the matrix (e.g., whether the matrix is invertible).

>Inverse: The matrix that, when multiplied by the original matrix, gives the identity matrix (for invertible matrices).

>Rank: The maximum number of linearly independent rows or columns in the matrix.

```
Practice Problem #1
```

In [3]:
import numpy as np


random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T


is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)

Random Matrix:
 [[5 2 2 5]
 [3 4 9 9]
 [2 9 4 3]
 [6 7 2 8]]

Is the random matrix symmetric?  False


```
Q3:
```

In [4]:
import numpy as np

example_matrix = np.array([[2, 4, 6],
                           [8, 10, 12],
                           [14, 16, 18]])

trace_example = np.trace(example_matrix)
print("\nTrace of the Example Matrix:", trace_example)



Trace of the Example Matrix: 30


```
Practice Problem 2
```

In [5]:
import numpy as np

identity_matrix = np.eye(5)
trace_identity = np.trace(identity_matrix)
print("5x5 Identity Matrix:\n", identity_matrix)
print("\nTrace of the Identity Matrix:", trace_identity)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of the Identity Matrix: 5.0


```
Practice Problem 3
```

In [6]:
import numpy as  np

matrix_B = np.array([[3, 1, 2],
                     [1, 4, 5],
                     [2, 5, 6]])

det_B = np.linalg.det(matrix_B)
print("\nDeterminant of Matrix B:", det_B)



Determinant of Matrix B: -4.999999999999994


```
Practice Problem 4
```


In [7]:
import numpy as np


pixel_matrix = np.random.randint(0, 256, (3, 3))
transpose_pixel = pixel_matrix.T
det_pixel = np.linalg.det(pixel_matrix)

print("Pixel Intensity Matrix:\n", pixel_matrix)
print("\nTranspose of Pixel Intensity Matrix:\n", transpose_pixel)
print("\nDeterminant of Pixel Intensity Matrix:", det_pixel)


Pixel Intensity Matrix:
 [[ 58 243 163]
 [198 249 207]
 [225 202  96]]

Transpose of Pixel Intensity Matrix:
 [[ 58 198 225]
 [243 249 202]
 [163 207  96]]

Determinant of Pixel Intensity Matrix: 3047274.0000000023


```
Practice Problem 5
```

In [8]:
import numpy as np

symmetric_matrix = np.array([[2, 1, 3],
                              [1, 5, 4],
                              [3, 4, 6]])


is_symmetric = (symmetric_matrix == symmetric_matrix.T).all()

print("Symmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric? ", is_symmetric)


Symmetric Matrix:
 [[2 1 3]
 [1 5 4]
 [3 4 6]]

Is the matrix symmetric?  True
