

```
Exercise 1: Matrix Addition & Subtraction
```



In [1]:
import numpy as np

# Define two 3x3 matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix Addition
addition_result = A + B
print("A + B:")
print(addition_result)

# Matrix Subtraction
subtraction_result = A - B
print("A - B:")
print(subtraction_result)

A + B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


```
Exercise 2: Matrix Multiplication
```

In [2]:
import numpy as np

# Define a 2x3 matrix F and a 3x2 matrix G
F = np.array([[1, 2, 3], [4, 5, 6]])
G = np.array([[7, 8], [9, 10], [11, 12]])

# Matrix Multiplication
multiplication_result = np.dot(F, G)
print("F * G (Matrix Multiplication):")
print(multiplication_result)

F * G (Matrix Multiplication):
[[ 58  64]
 [139 154]]


```
Exercise 3: Matrix Transpose
```

In [3]:
import numpy as np

# Define a 2x3 matrix
Z = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose of the matrix
transpose_result = Z.T
print("Transpose of Z:")
print(transpose_result)

Transpose of A:
[[1 4]
 [2 5]
 [3 6]]


```
Exercise 4: Calculating the Determinant
```

In [4]:
import numpy as np

# Define a 3x3 matrix
M = np.array([[1, 2, 3], [0, 4, 5], [1, 0, 6]])

# Calculate the determinant of M
determinant_result = np.linalg.det(M)
print("Determinant of M:", determinant_result)


Determinant of M: 22.000000000000004


```
Exercise 5: Finding the Inverse
```

In [5]:
import numpy as np

# Define a 3x3 invertible matrix
H = np.array([[4, 7, 2], [3, 5, 1], [2, 8, 6]])

# Calculate the inverse of H
inverse_result = np.linalg.inv(H)
print("Inverse of H:")
print(inverse_result)


Inverse of H:
[[ 5.5  -6.5  -0.75]
 [-4.    5.    0.5 ]
 [ 3.5  -4.5  -0.25]]


```
1. Matrix Creation and Structure
```

>> Question: Explain what a matrix is and provide an example of a 3×2 matrix. Using NumPy, write code to create this matrix.

>> Answer: Explanation: A matrix is a two-dimensional array of numbers arranged in rows and columns. It is often represented in the form of a rectangular array, where each element is denoted by its position (row, column). Matrices are used in many areas of mathematics, physics, and computer science, especially in solving systems of equations and performing linear transformations.


In [8]:
import numpy as np

# Create a 3x2 matrix
AA = np.array([[1, 2], [3, 4], [5, 6]])

print("3x2 Matrix AA:")
print(AA)


3x2 Matrix AA:
[[1 2]
 [3 4]
 [5 6]]


```
2. Basic Matrix Operations
```
>> Question: Given two matrices A and B, describe the conditions necessary for performing matrix addition and matrix multiplication.

>> Answer: Matrix Addition: To add two matrices, the matrices must have the same dimensions (same number of rows and columns). Each element of the resulting matrix is the sum of the corresponding elements in the two matrices.

>> Matrix Multiplication: To multiply two matrices, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The element at position (i, j) in the resulting matrix is obtained by computing the dot product of the i-th row of the first matrix and the j-th column of the second matrix.

In [10]:
import numpy as np

# Create two 5x5 matrices
AAA = np.random.randint(1, 10, (5, 5))
BBB = np.random.randint(1, 10, (5, 5))

# Matrix Addition
addition_result = AAA + BBB
print("AAA + BBB (Matrix Addition):")
print(addition_result)

# Matrix Multiplication
multiplication_result = np.dot(AAA, BBB)
print("AAA * BBB (Matrix Multiplication):")
print(multiplication_result)


AAA + BBB (Matrix Addition):
[[ 8 11 10 13  3]
 [12 12 12 12  6]
 [17 11  3 11 15]
 [12  7  8 15 10]
 [ 9  8 14 13 10]]
AAA * BBB (Matrix Multiplication):
[[143  77 111  91  96]
 [201 116 151 130 145]
 [153 113 179 135 120]
 [165  89 138 112 118]
 [223 156 182 154 161]]


```
3. Transpose of a Matrix
```

>> Question: Explain the concept of matrix transposition. What effect does it have on a 3×2 matrix? Write code to create a 3×2 matrix and find its transpose.

>> Answer: The transpose of a matrix is a new matrix formed by switching its rows with its columns. The transpose of a matrix \( A \) is represented as \( A^T \).



In [12]:
import numpy as np

# Create a 3x2 matrix
AAAA = np.array([[1, 2], [3, 4], [5, 6]])

# Find the transpose of A
transpose_result = AAAA.T
print("Transpose of AAAA:")
print(transpose_result)


Transpose of AAAA:
[[1 3 5]
 [2 4 6]]


```
4. Working with Large Matrices
```

>>Question: Create a random 5×5 matrix using NumPy. Compute the sum of all elements in the matrix, then find its transpose. Print both the sum and the transpose of the matrix.


In [15]:
import numpy as np

# Create a random 5x5 matrix
matrix = np.random.randint(1, 100, (5, 5))

# Compute the sum of all elements in the matrix
matrix_sum = np.sum(matrix)

# Find the transpose of the matrix
transpose_result = matrix.T

# Print the results
print("5x5 Random Matrix:")
print(matrix)
print("\n")
print("Sum of all elements in the matrix:", matrix_sum)
print("\n")
print("Transpose of the matrix:")
print(transpose_result)

5x5 Random Matrix:
[[48 14 36 36 75]
 [85 32 96 74 24]
 [26 23 74 98 53]
 [18 50 54 22 70]
 [ 9 46 39 28 55]]


Sum of all elements in the matrix: 1185


Transpose of the matrix:
[[48 85 26 18  9]
 [14 32 23 50 46]
 [36 96 74 54 39]
 [36 74 98 22 28]
 [75 24 53 70 55]]


```
5. Applying Matrix Operations in Context
```

>>Question: Suppose you have two random 10×10 matrices D and E. Write code to (a) add the matrices, (b) subtract E from D, and (c) multiply D and E using matrix multiplication. Print each result and describe one possible application of each operation in computer science.


In [17]:
import numpy as np

# Create two random 10x10 matrices
D = np.random.randint(1, 10, (10, 10))
E = np.random.randint(1, 10, (10, 10))

# Matrix Addition
addition_result = D + E
print("D + E (Matrix Addition):")
print(addition_result)
print("\n")
# Matrix Subtraction
subtraction_result = D - E
print("D - E (Matrix Subtraction):")
print(subtraction_result)
print ("\n")
# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)


D + E (Matrix Addition):
[[14  5  3 10 13 16 11  8 10 14]
 [10 10 10  7 11 10 12  8  4 18]
 [ 9  6  5  3  8 10 15 10  9 13]
 [15 13 15 11 12 11  9  6  9 10]
 [ 5  4  6 11  2 12  9 10 10 13]
 [13  9 10  9  4  9  3  6 15  5]
 [ 6 12  4 14  8 14 12 11  9  6]
 [14  4  5  8  7 14  7  7 15  8]
 [11  5 16 12 10 10  7 17 17  4]
 [17  6 13 11  2 12 11 11  6 11]]


D - E (Matrix Subtraction):
[[-4 -3 -1 -2  5  2 -7 -4  6 -4]
 [ 0  6 -8 -1  7  2  2  2 -2  0]
 [ 5  0  3  1  0  0 -3  4  7 -3]
 [ 1 -3 -3  1 -6  1 -1 -4  1  4]
 [ 3  0  2  5  0 -4  5 -2 -8 -1]
 [-3 -5  6 -7  2 -7 -1 -4 -1 -1]
 [-4 -6  2  0  4  4 -2 -3 -3 -2]
 [ 0  0 -1 -4  1 -4  1  1  1  6]
 [ 5 -3  0 -6 -4  8 -5 -1 -1 -2]
 [-1  2  3 -7  0  0 -1  5  4 -1]]


D * E (Matrix Multiplication):
[[254 202 189 297 151 274 213 262 286 228]
 [319 218 215 322 127 342 263 256 271 305]
 [292 215 197 321 171 294 283 272 273 256]
 [307 228 221 303 182 284 302 256 219 296]
 [263 213 169 247 152 244 235 196 176 200]
 [140 112 123 162 125 153 204 167 1